# Generated by Django 3.1 on 2020-10-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('key', models.CharField(max_length=150)),
                ('key_type', models.CharField(choices=[('API_KEY', 'API Key'), ('APP_KEY', 'Application Key')], max_length=25)),
            ],
            options={
                'verbose_name': 'authentication_key',
                'verbose_name_plural': 'authentication_keys',
            },
        ),
    ]
